export function getPortalGuideText(lang: 'ar' | 'en', productName?: string) {
  const guideText = lang === 'ar' ? {
    modalTitle: `شرح ${productName || 'المنتج'}`,
    close: 'إغلاق نافذة الشرح',
    tutorialTitle: `شرح ${productName || 'المنتج'}`,
    tutorialDescription: 'شرح مرئي كامل يوضح طريقة التفعيل والتشغيل خطوة بخطوة.',
    issueFixesTitle: 'إصلاح المشاكل الشائعة',
    issueFixesDescription: 'شروحات مرئية لأخطاء الشبكة والوقت.',
    issuesLabel: 'مكتبة حلول المشاكل',
    issuesTitle: 'مكتبة الشروحات المرئية',
    issuesDescription: 'اختر الشرح المناسب من المكتبة. كل بطاقة تعرض صورة الخطأ ثم تفتح فيديو الحل المطابق لها داخل الموقع.',
    libraryAvailable: '4 حلول متاحة',
    videoGuide: 'شرح فيديو',
    runtimeIssueTitle: 'خطأ تعريفات Visual C++ أو رسالة بيضاء',
    runtimeIssueDescription: 'لرسائل VCRUNTIME140_1.dll أو MSVCP140.dll غير الموجودة عند تشغيل اللودر أو البرنامج.',
    runtimeIssueAction: 'تحميل Visual C++ x64',
    runtimeIssueHint: 'تنزيل رسمي من Microsoft ثم أعد تشغيل Windows قبل تجربة المنتج.',
    commonErrorsTitle: 'حل سريع لرسائل التشغيل الشائعة',
    commonErrorsDescription: 'إذا ظهرت شاشة تحميل بيضاء أو رسالة فقدان ملف DLL عند فتح اللودر، ابدأ بتحديث تعريفات Visual C++ الرسمية ثم أعد تشغيل Windows.',
    commonErrorsAction: 'تحميل وتحديث Visual C++ x64',
    commonErrorsNote: 'يشمل أخطاء VCRUNTIME140_1.dll وVCRUNTIME140.dll وMSVCP140.dll.',
    runtimePreviewLabel: 'مثال رسالة الخطأ',
    runtimePreviewDescription: 'إذا ظهرت نافذة مشابهة، ثبّت تعريفات Visual C++ من الزر أعلاه ثم أعد تشغيل Windows.',
    runtimePreviewStepOne: 'نزّل التعريف الرسمي.',
    runtimePreviewStepTwo: 'ثبّته ثم أعد التشغيل.',
    runtimePreviewStepThree: 'شغّل اللودر من جديد.',
    downloadWarpLabel: 'أداة اتصال اختيارية',
    downloadWarp: 'تحميل Cloudflare WARP لنظام Windows',
    downloadWarpAction: 'تنزيل الآن',
    downloadWarpHint: 'قد يساعد في استعادة اتصال الشبكة قبل متابعة الشرح.',
    networkIssueTitle: 'مشكلة الشبكة أو إيقاف الواي فاي',
    networkIssueDescription: 'عند ظهور رسالة عدم الوصول إلى اسم المضيف أو فشل اتصال الشبكة.',
    timeIssueTitle: 'خطأ الوقت والتحقق',
    timeIssueDescription: 'عند ظهور تنبيه مزامنة وقت ويندوز أو فشل التحقق من التوقيع.',
    spooferIssueTitle: 'مشكلة عدم ظهور قائمة Spoofer',
    spooferIssueDescription: 'عندما يظهر أن WebUI يعمل لكن قائمة Spoofer لا تظهر داخل الواجهة.',
    watchSolution: 'مشاهدة فيديو الحل',
    solutionVideoLabel: 'فيديو الحل',
    screenshotLabel: 'صورة الخطأ المرجعية',
    noticeLabel: 'تنبيه قبل مشاهدة الشرح',
    noticeHint: 'اقرأ قبل المتابعة',
    noticeTitle: 'مهم قبل البدء',
    introBefore: 'هنا يتم شرح ',
    introProduct: `كامل خطوات منتج ${productName || 'المنتج'}`,
    introMiddle: '. يرجى اتباع الشرح بالكامل وبنفس الترتيب ',
    introEmphasis: 'دون تخطي أي خطوة',
    introAfter: '، لضمان تنفيذ العملية بالشكل الصحيح وتجنب أي مشاكل.',
    importantTitle: 'تنبيه مهم',
    importantPrimaryBefore: 'إدارة الموقع وكذلك ',
    storeName: 'متجر تعن',
    importantPrimaryAfter: ' لا تتحمل مسؤولية فقدان المفتاح أو استخدامه بشكل خاطئ.',
    preparationTitle: 'تجهيز إلزامي قبل البدء',
    preparationDescription: 'يلزم تجهيز فلاش USB بنسخة Windows المناسبة قبل متابعة شرح المنتج. أكمل هذه الخطوة أولاً ثم تابع الفيديو الرئيسي.',
    windows11Label: 'تجهيز فلاش Windows 11',
    windows10Label: 'تجهيز فلاش Windows 10',
    watchPreparation: 'مشاهدة شرح التجهيز',
    motherboardTitle: 'تنبيه توافق اللوحة الأم',
    motherboardDescription: 'إذا لم تكتمل العملية بعد اتباع الدليل وتجهيز Windows، فقد يرتبط ذلك بقيود توافق في اللوحة الأم. لا يمكن ضمان إمكانية تغيير معلومات الجهاز عند وجود هذه القيود.',
    formatSectionTitle: 'تجهيز فلاش Windows',
    formatSectionDescription: 'قسم مستقل لتحضير فلاش USB بنسخة Windows المناسبة قبل متابعة دليل المنتج.',
    formatSectionAction: 'فتح قسم تجهيز الفلاش',
    waitingTitle: 'الخطوة الأخيرة قبل الفيديو',
    readyTitle: 'أصبح الشرح جاهزًا للمشاهدة',
    waitingMessage: (seconds: number) => `يرجى قراءة التنبيه. سيتاح زر المتابعة بعد ${seconds} ${seconds === 1 ? 'ثانية' : 'ثوانٍ'}.`,
    readyMessage: 'تمت قراءة التنبيه. يمكنك الآن متابعة شرح الفيديو.',
    waitingButton: (seconds: number) => `انتظر ${seconds} ثوانٍ`,
    continueButton: 'قرأت التنبيه — متابعة',
    back: 'العودة للقائمة السابقة',
    unavailableTitle: 'لا يوجد فيديو شرح متاح',
    unavailableMessage: 'لم تقم الإدارة بإضافة رابط فيديو شرح لهذا المنتج حتى الآن.',
  } : {
    modalTitle: `${productName || 'Product'} Guide`,
    close: 'Close tutorial dialog',
    tutorialTitle: `${productName || 'Product'} Guide`,
    tutorialDescription: 'A complete visual walkthrough for activation and setup, step by step.',
    issueFixesTitle: 'Common issue fixes',
    issueFixesDescription: 'Visual guides for network and system-time errors.',
    issuesLabel: 'TROUBLESHOOTING LIBRARY',
    issuesTitle: 'Visual troubleshooting library',
    issuesDescription: 'Choose the relevant guide from the library. Each card shows the error screenshot and opens its dedicated solution video inside the site.',
    libraryAvailable: '4 fixes available',
    videoGuide: 'Video guide',
    runtimeIssueTitle: 'Visual C++ runtime or white error message',
    runtimeIssueDescription: 'For missing VCRUNTIME140_1.dll or MSVCP140.dll messages when opening the loader or application.',
    runtimeIssueAction: 'Download Visual C++ x64',
    runtimeIssueHint: 'Official Microsoft download. Restart Windows before trying the product again.',
    commonErrorsTitle: 'Quick fix for common launch errors',
    commonErrorsDescription: 'If a white loading screen or a missing DLL message appears when opening the loader, update the official Visual C++ runtime and restart Windows.',
    commonErrorsAction: 'Download & update Visual C++ x64',
    commonErrorsNote: 'Covers VCRUNTIME140_1.dll, VCRUNTIME140.dll, and MSVCP140.dll errors.',
    runtimePreviewLabel: 'Example error message',
    runtimePreviewDescription: 'If you see a similar window, install the Visual C++ runtime from the button above, then restart Windows.',
    runtimePreviewStepOne: 'Download the official runtime.',
    runtimePreviewStepTwo: 'Install it, then restart.',
    runtimePreviewStepThree: 'Start the loader again.',
    downloadWarpLabel: 'OPTIONAL CONNECTION TOOL',
    downloadWarp: 'Download Cloudflare WARP for Windows',
    downloadWarpAction: 'Download now',
    downloadWarpHint: 'It may help restore your network connection before continuing the guide.',
    networkIssueTitle: 'Network or Wi-Fi connection error',
    networkIssueDescription: 'For hostname resolution failures or a network connection error.',
    timeIssueTitle: 'System time and verification error',
    timeIssueDescription: 'For Windows time-sync prompts or signature verification failures.',
    spooferIssueTitle: 'Spoofer list is not appearing',
    spooferIssueDescription: 'When WebUI is running but the Spoofer list does not appear in the interface.',
    watchSolution: 'Watch solution video',
    solutionVideoLabel: 'SOLUTION VIDEO',
    screenshotLabel: 'REFERENCE ERROR SCREENSHOT',
    noticeLabel: 'Before you watch',
    noticeHint: 'Please read before continuing',
    noticeTitle: 'Important before you begin',
    introBefore: 'This tutorial explains ',
    introProduct: `the complete ${productName || 'product'} process`,
    introMiddle: '. Please follow every step in the exact order ',
    introEmphasis: 'without skipping any step',
    introAfter: ', to help ensure the process is completed correctly and avoid issues.',
    importantTitle: 'Important notice',
    importantPrimaryBefore: 'The website administration and ',
    storeName: 'Ta3n Store',
    importantPrimaryAfter: ' are not responsible for lost keys or incorrect use.',
    preparationTitle: 'Required preparation',
    preparationDescription: 'Prepare a USB flash drive with the appropriate Windows version before continuing with the product guide. Complete this first, then continue to the main video.',
    windows11Label: 'Prepare a Windows 11 USB',
    windows10Label: 'Prepare a Windows 10 USB',
    watchPreparation: 'Watch preparation guide',
    motherboardTitle: 'Motherboard compatibility notice',
    motherboardDescription: 'If the process does not complete after following the guide and preparing Windows, it may relate to motherboard compatibility restrictions. These restrictions can prevent changes to device information.',
    formatSectionTitle: 'Prepare a Windows USB',
    formatSectionDescription: 'A separate section for preparing a USB drive with the appropriate Windows version before the product guide.',
    formatSectionAction: 'Open USB preparation',
    waitingTitle: 'One final step before the video',
    readyTitle: 'The tutorial is ready to watch',
    waitingMessage: (seconds: number) => `Please read this notice. Continue will unlock in ${seconds} ${seconds === 1 ? 'second' : 'seconds'}.`,
    readyMessage: 'You have read the notice. You can now continue to the video tutorial.',
    waitingButton: (seconds: number) => `Wait ${seconds}s`,
    continueButton: 'I understand — continue',
    back: 'Back to guide options',
    unavailableTitle: 'No tutorial video is available',
    unavailableMessage: 'The administration has not added a tutorial video for this product yet.',
  };
  return guideText;
}
