'use client';
import { useCallback, useEffect, useState } from 'react';
import { PERMISSION_KEYS } from '@/lib/permissions';

type RoleRow = { role: string; permissions: string[]; userCount: number; editable: boolean };
export function RoleManager({ lang, onNotify }: { lang: string; onNotify: (message: string, type?: 'success' | 'error') => void }) {
  const [roles, setRoles] = useState<RoleRow[]>([]);
  const [busy, setBusy] = useState(true);
  const [saving, setSaving] = useState<string | null>(null);
  const ar = lang === 'ar';
  const labels: Record<string, string> = { 'dashboard.view':'لوحة المعلومات', 'users.view':'عرض العملاء', 'users.edit':'تعديل العملاء', 'users.disable':'تعطيل العملاء', 'products.view':'عرض المنتجات', 'products.create':'إنشاء المنتجات', 'products.edit':'تعديل المنتجات', 'products.delete':'حذف المنتجات', 'keys.view':'عرض المفاتيح', 'keys.create':'إنشاء المفاتيح', 'keys.disable':'إلغاء المفاتيح', 'keys.reset':'إعادة ضبط المفاتيح', 'inventory.view':'عرض المخزون', 'inventory.edit':'تعديل المخزون', 'faq.view':'عرض الأسئلة', 'faq.create':'إنشاء الأسئلة', 'faq.edit':'تعديل الأسئلة', 'faq.delete':'حذف الأسئلة', 'announcements.view':'عرض الإعلانات', 'announcements.create':'إنشاء الإعلانات', 'announcements.publish':'نشر الإعلانات', 'announcements.delete':'حذف الإعلانات', 'roles.view':'عرض الأدوار', 'roles.manage':'إدارة الأدوار', 'logs.view':'عرض السجلات', 'settings.view':'عرض الإعدادات', 'settings.edit':'تعديل الإعدادات' };
  const load = useCallback(async () => { try { const response = await fetch('/api/admin/roles', { cache: 'no-store' }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setRoles(data.roles); } catch (error) { onNotify(error instanceof Error ? error.message : 'تعذر تحميل الأدوار', 'error'); } finally { setBusy(false); } }, [onNotify]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function save(role: RoleRow) { setSaving(role.role); try { const response = await fetch('/api/admin/roles', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ role: role.role, permissions: role.permissions }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); onNotify(ar ? 'تم حفظ صلاحيات الدور' : 'Role permissions saved'); } catch (error) { onNotify(error instanceof Error ? error.message : 'تعذر الحفظ', 'error'); } finally { setSaving(null); } }
  if (busy && !roles.length) return <div className="p-6">{ar ? 'جارٍ تحميل الأدوار…' : 'Loading roles…'}</div>;
  return <div className="space-y-5">{roles.map((role) => <section key={role.role} className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><header className="mb-4 flex items-center justify-between"><div><h3 className="font-bold">{role.role}</h3><p className="text-xs opacity-60">{role.userCount} {ar ? 'مستخدم' : 'users'} · {role.permissions.length} {ar ? 'صلاحية' : 'permissions'}</p></div>{role.editable && <div className="flex items-center gap-2"><button onClick={() => setRoles((current) => current.map((item) => item.role === role.role ? { ...item, permissions: [...PERMISSION_KEYS] } : item))} className="rounded-lg border border-white/10 px-3 py-2 text-xs">{ar ? 'تحديد الكل' : 'Select all'}</button><button onClick={() => setRoles((current) => current.map((item) => item.role === role.role ? { ...item, permissions: [] } : item))} className="rounded-lg border border-white/10 px-3 py-2 text-xs">{ar ? 'مسح الكل' : 'Clear all'}</button><button disabled={saving === role.role} onClick={() => void save(role)} className="rounded-lg bg-cyan-500 px-4 py-2 text-sm font-bold text-slate-950 disabled:opacity-50">{saving === role.role ? '…' : ar ? 'حفظ' : 'Save'}</button></div>}</header><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{PERMISSION_KEYS.map((permission) => <label key={permission} className="flex items-center gap-2 rounded-lg bg-black/10 p-2 text-sm"><input type="checkbox" disabled={!role.editable} checked={role.permissions.includes(permission)} onChange={(event) => setRoles((current) => current.map((item) => item.role === role.role ? { ...item, permissions: event.target.checked ? [...item.permissions, permission] : item.permissions.filter((value) => value !== permission) } : item))} /><span>{ar ? labels[permission] : permission}</span></label>)}</div></section>)}</div>;
}
