import { Product } from '@/types';

export const initialProducts: Product[] = [
  {
    id: 'prod-fortnite',
    name: 'فك باند فورت نايت',
    description: 'يقوم بتغيير معلومات جهازك إلى معلومات جديدة لإلغاء الحظر في لعبة فورت نايت نهائيًا.\n\nالمميزات:\n- فك باند فورت نايت.\n- فك باند البطولات.\n- نسبة نجاح 100%.\n- فك باند دائم.',
    image: '/products/fortnite-unban.png',
    cardColor: 'blue',
    category: 'Spoofer',
    displayOrder: 1,
    version: 'v3.5.2',
    fileSize: '24.8 MB',
    fileUrl: '/discord.gg_t3n.rar',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    guideUrl: 'https://discord.gg/t3n',
    downloadsCount: 1420,
    isVisible: true,
    isDisabled: false,
    isArchived: false,
    createdAt: '2026-01-15T00:00:00.000Z',
    updatedAt: '2026-01-15T00:00:00.000Z',
  },
  {
    id: 'prod-hwid-master',
    name: 'سبوفر تعن',
    description: '100% مضمون وموثوق\n\nيقوم بتغيير معلومات جهازك إلى معلومات جديدة، لإلغاء الحظر الهاردوير في أي لعبة نهائيًا.\n\nالمميزات:\n- نسبة نجاح 100%.\n- فك باند دائم.',
    image: '/products/spoofer-ta3n.png',
    cardColor: 'purple',
    category: 'PERM',
    displayOrder: 2,
    version: 'v4.1.0',
    fileSize: '100 MB',
    fileUrl: '/discord.gg_t3n.rar',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    guideUrl: 'https://discord.gg/t3n',
    downloadsCount: 980,
    isVisible: true,
    isDisabled: false,
    isArchived: false,
    createdAt: '2026-01-20T00:00:00.000Z',
    updatedAt: '2026-01-20T00:00:00.000Z',
  },
  {
    id: 'prod-spoofer-vip',
    name: 'Spoofer VIP',
    description: 'إصدار VIP من منتج Spoofer، يستخدم ملف التنزيل ومكتبة الشروحات وحلول المشاكل المعتمدة نفسها. عند تفعيل المفتاح تُمنح رتبة Customer VIP تلقائيًا في ديسكورد.',
    image: '/spoofer-logo.png',
    cardColor: 'gold',
    category: 'VIP',
    displayOrder: 3,
    version: 'v4.1.0',
    fileSize: '100 MB',
    fileUrl: '/discord.gg_t3n.rar',
    videoUrl: 'https://files.manuscdn.com/user_upload_by_module/session_file/310519663152548301/mHiKjOdRBJBDsCnu.mp4',
    guideUrl: 'https://t3nn.wtf',
    downloadsCount: 0,
    isVisible: true,
    isDisabled: false,
    isArchived: false,
    createdAt: '2026-08-22T00:00:00.000Z',
    updatedAt: '2026-08-22T00:00:00.000Z',
  }
];
